In [3]:
import json
import glob
import pandas as pd
import numpy as np
import tqdm
from sklearnex import patch_sklearn
patch_sklearn()
import sklearn
from numpy import asarray
from PIL import Image
import torch
from torchvision.transforms import ToTensor
from torch import flatten
import os
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

images = '/Users/paddy/Desktop/AiCore/facebook_ml/images_raw'
images_corrected = '/Users/paddy/Desktop/AiCore/facebook_ml/Images'
data = '/Users/paddy/Desktop/AiCore/facebook_ml/final_dataset/image_data.json'

Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)


In [4]:
image_list = glob.glob(f'{images}/*.jpg')
df = pd.read_json(data)
df

image_id  category
0      912bb259-3ad9-457b-9db1-ce1da9016057         6
1      b166d305-b852-4bdd-83f4-465b20da94fa         6
2      68f5a29d-0075-4d60-81c1-ab684a82e50c         6
3      f6a309d7-d247-446a-9b5e-aceefdd4334d         6
4      2c2b3a6f-15b3-4289-937a-15482d9f5781         6
...                                     ...       ...
12599  cdec1c5c-c4b1-42db-afbe-3fa68ea4b87d        12
12600  dc99e40f-6b15-494d-9fb7-f0d02e9781f9        12
12601  c8488028-bf07-4258-a4c2-56d2fe387835        12
12602  c6113145-89c8-47cd-9211-38f29d016cc7        12
12603  ed2aaf88-616c-4e6b-af49-bbdf7c0fbd06        12

[10188 rows x 2 columns]

In [22]:
image_id =  df['image_id'].to_numpy()
def image_correct_prop():
        resized_img = 128
        for img in range(len(image_id)):
            image_ite = Image.open(f'{images}/{image_id[img]}.jpg')
            background = Image.new(mode='RGB', size=(resized_img, resized_img)) 
            original_img = image_ite.size
            max_dim = max(image_ite.size)
            ratio = resized_img / max_dim
            img_corr_ratio =(int(original_img[0] * ratio), int(original_img[1] * ratio))
            img_corr = image_ite.resize(img_corr_ratio)
            # print(img_corr)
            background.paste(img_corr, (((resized_img - img_corr_ratio[0]) // 2), ((resized_img - img_corr_ratio[1]) // 2)))
            # print(background)
            background.save(f'{images_corrected}/{image_id[img]}.jpg')
# image_correct_prop()
vfunc = np.vectorize(image_correct_prop())

In [29]:
image_array = []
image_classification = df['category'].to_numpy()

def image_to_tensor():
        for img in image_id:
            image = Image.open(f'{images_corrected}/{img}.jpg')
            print(image)
            t = ToTensor()
            tensor = t(image)
            flattened = torch.flatten(tensor)
            flatten_numpy = flattened.numpy()
            # print(flattened.dtype)
            
            image_array.append(flatten_numpy)
            # index_of_image = image_id.values()
            # image_tuple = ((image_array, index_of_image))
            # image_array.append(image_tuple)
            # print(empty)
            print(flatten_numpy)
        return image_array
image_to_tensor()
print(len(image_array))


<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=128x128 at 0x7FE36DD86C40>
[0. 0. 0. ... 0. 0. 0.]
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=128x128 at 0x7FE3680C87F0>
[0. 0. 0. ... 0. 0. 0.]
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=128x128 at 0x7FE3680A5B50>
[0. 0. 0. ... 0. 0. 0.]
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=128x128 at 0x7FE36DD438E0>
[0. 0. 0. ... 0. 0. 0.]
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=128x128 at 0x7FE3680A5B50>
[0. 0. 0. ... 0. 0. 0.]
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=128x128 at 0x7FE36DD435E0>
[0. 0. 0. ... 0. 0. 0.]
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=128x128 at 0x7FE3680A5B50>
[0. 0. 0. ... 0. 0. 0.]
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=128x128 at 0x7FE36AC5FF10>
[0. 0. 0. ... 0. 0. 0.]
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=128x128 at 0x7FE367FF8FD0>
[0. 0. 0. ... 0. 0. 0.]
<PIL.JpegImagePlugin.JpegImageFile image mode=

In [30]:
list_of_tuples = []

def joiner():
    for i in range(len(image_array)):
        classification = image_classification[i]
        image_tuple = image_array[i], classification
        list_of_tuples.append(image_tuple)
        print(image_tuple)
    return
joiner()
print(list_of_tuples)

(array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), 6)
(array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), 6)
(array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), 6)
(array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), 6)
(array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), 6)
(array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), 6)
(array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), 6)
(array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), 6)
(array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), 6)
(array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), 6)
(array([0.02745098, 0.7882353 , 0.7764706 , ..., 0.76862746, 0.78431374,
       0.01568628], dtype=float32), 6)
(array([0.00392157, 0.00392157, 0.00392157, ..., 0.00784314, 0.00784314,
       0.        ], dtype=float32), 6)
(array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), 6)
(array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), 6)
(array([1., 1., 1., ..., 1., 1., 1.], dtype=float32), 6)
(array([0., 0., 0., ..., 0., 0., 0.

In [31]:
print(list_of_tuples[0])

(array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), 6)


In [32]:
m = len(list_of_tuples)
sh = image_array[0].shape
array_size = 49152
list_of_tuples
print(len(list_of_tuples))
X = np.zeros((m, array_size))
y = np.zeros(m)
print(X.shape, y.shape)
for item in range(m):
    features, labels = list_of_tuples[item]
    # print(features.shape)
    X[item, :] = features
    y[item] = labels
    # print(X)
    print(y)

10188
(10188, 49152) (10188,)
[6. 0. 0. ... 0. 0. 0.]
[6. 6. 0. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. ... 0. 0. 0.]
[6. 6. 6. 

In [33]:
model = LogisticRegression(max_iter= 100)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=37)
model.fit(X_train, y_train)
pred = model.predict(X_test)
print ('accuracy:', accuracy_score(y_test, pred))
print('report:', classification_report(y_test, pred))

/Users/paddy/opt/anaconda3/lib/python3.8/site-packages/daal4py/sklearn/linear_model/logistic_path.py:459: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


accuracy: 0.15014720314033367
report:               precision    recall  f1-score   support

         0.0       0.10      0.09      0.10       148
         1.0       0.08      0.07      0.07       116
         2.0       0.14      0.13      0.13       129
         3.0       0.23      0.21      0.22       182
         4.0       0.15      0.16      0.15       139
         5.0       0.15      0.21      0.18       180
         6.0       0.17      0.19      0.18       248
         7.0       0.14      0.14      0.14       141
         8.0       0.20      0.18      0.19       170
         9.0       0.11      0.12      0.11       137
        10.0       0.15      0.16      0.16       131
        11.0       0.16      0.15      0.16       161
        12.0       0.10      0.07      0.08       156

    accuracy                           0.15      2038
   macro avg       0.14      0.14      0.14      2038
weighted avg       0.15      0.15      0.15      2038

